export const EVENT_NAME = {
  PBJS_AUCTION_INIT: "AUCTION_INIT",
  PBJS_AUCTION_END: "AUCTION_END",
  PBJS_SET_TARGETING: "SET_KV",
  PBJS_WON: "WON",
  GOOGLE_REQUEST: "REQUEST",
  PBJS_ERROR: "PBJS_ERROR",
  PBJS_BIDDER_ERROR: "PBJS_BIDDER_ERROR",
} as const;
